### ISSUE TITLE
Login (semi-) permanently

### ISSUE THREAD

**Issue by bobness** [bobness/inspect-app#13]
Perhaps with a timeout

so sharing into Inspect and background notifications work

**Comment by dreitec** [comment]
Pushed changes to `[fix/keep-login-and-suggest-user](https://github.com/bobness/inspect-app/tree/fix/keep-login-and-suggest-user)` branch for inspect-app.
For the BE changes, I've pushed all changes to `[fix/suggest-user](https://github.com/bobness/inspect-service/tree/fix/suggest-user)` branch for inspect-service
