### ISSUE TITLE
Suggest user to follow when home empty

### ISSUE THREAD

**Issue by bobness** [bobness/inspect-app#14]

**Comment by dreitec** [comment]
Pushed changes to [fix/keep-login-and-suggest-user](https://github.com/bobness/inspect-app/tree/fix/keep-login-and-suggest-user) branch for inspect-app.
For the BE changes, I've pushed all changes to [fix/suggest-user](https://github.com/bobness/inspect-service/tree/fix/suggest-user) branch for inspect-service
